<a href="https://colab.research.google.com/github/MayankSangwan07/QM_ASSIGNMENTS/blob/main/MAYANK_102316070_QUANTUM_COMPUTING_ASSIGNMENT_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import math
a = 1/math.sqrt(2)
b = 1/math.sqrt(2)

vector = np.array([a,b])
print(vector)

# checking that whether the vector is normalized or not
normlaized_value = a**2 + b**2

if math.isclose(normlaized_value,1.0):
  print("The vector is normlaized vector")
else:
  print("The vector is not normlaized vector")

# now finding the length (magnitude) of the vector
length = np.linalg.norm(vector)
length2 = math.sqrt(normlaized_value)
print(length)
print(length2)

[0.70710678 0.70710678]
The vector is normlaized vector
0.9999999999999999
0.9999999999999999


In [3]:
def is_normalized(vector):
  magnitude = np.linalg.norm(vector)
  if math.isclose(magnitude,1.0):
    print("The vector is normlaized vector")
  else:
    print("The vector is not normlaized vector")


def np_dot_cross_product(vector1,vector2):
  dot_product = np.dot(vector1,vector2)
  cross_product = np.cross(vector1,vector2)

  return dot_product,cross_product


def unit_vector(vector1):
  magnitude = np.linalg.norm(vector1)
  if magnitude == 0:
        return "Zero vector has no unit vector"1

  unit_vector = vector1/magnitude

  return unit_vector

def read_value():
  n = int(input("enter the number of values in vector : "))
  elements = []

  for i in range(n):
    element = float(input("enter the value :"))
    elements.append(element)

  return np.array(elements)


A = read_value()
B = read_value()

print(A)
print(B)


is_normalized(A)
is_normalized(B)


print("the dot product and cross product : ",np_dot_cross_product(A,B))

print(unit_vector(A))
print(unit_vector(B))




enter the number of values in vector : 3
enter the value :3
enter the value :2
enter the value :1
enter the number of values in vector : 3
enter the value :1
enter the value :2
enter the value :3
[3. 2. 1.]
[1. 2. 3.]
The vector is not normlaized vector
The vector is not normlaized vector
the dot product and cross product :  (np.float64(10.0), array([ 4., -8.,  4.]))
[0.80178373 0.53452248 0.26726124]
[0.26726124 0.53452248 0.80178373]


In [7]:
def read_matrix():
  m = int(input("enter the number of rows : "))
  n = int(input("enter the number of columns : "))

  matrix = []

  for i in range(m):
    row = []
    for j in range(n):
      value = float(input(f"Enter element [{i}][{j}]: "))
      row.append(value)
    matrix.append(row)

  return np.array(matrix)


def transpose_matrix(matrix):
  return matrix.T

def determinant_matrix(matrix):
  if matrix.shape[0] != matrix.shape[1]:
    return "Determinant is defined only for the square matrices"
  return np.linalg.det(matrix)

def rank_matrix(matrix):
  if matrix.shape[0] != matrix.shape[1]:
    return "Rank is defined only for the square matrices"
  return np.linalg.matrix_rank(matrix) #or np.trace(matrix)

def eigen_matrix(matrix):
  if matrix.shape[0] != matrix.shape[1]:
    return "Eigen values and eigen vectors are defined only for the square matrices"
  eigen_values,eigen_vectors = np.linalg.eig(matrix)
  return eigen_values,eigen_vectors

def inverse_matrix(matrix):
  if matrix.shape[0] != matrix.shape[1]:
    return "Inverse is defined only for the square matrices"
  if np.linalg.det(matrix) == 0:
      return "Matrix is singular; inverse does not exist"
  return np.linalg.inv(matrix)

A = read_matrix()

print("\nMatrix A:")
print(A)

print("\nTranspose:")
print(transpose_matrix(A))

print("\nDeterminant:")
print(determinant_matrix(A))

print("\nRank:")
print(rank_matrix(A))

print("\nTrace:")
print(rank_matrix(A))

print("\nEigenvalues and Eigenvectors:")
print(eigen_matrix(A))

print("\nInverse:")
print(inverse_matrix(A))




enter the number of rows : 3
enter the number of columns : 3
Enter element [0][0]: 1
Enter element [0][1]: 2
Enter element [0][2]: 3
Enter element [1][0]: 2
Enter element [1][1]: 2
Enter element [1][2]: 1
Enter element [2][0]: 1
Enter element [2][1]: 2
Enter element [2][2]: 4

Matrix A:
[[1. 2. 3.]
 [2. 2. 1.]
 [1. 2. 4.]]

Transpose:
[[1. 2. 1.]
 [2. 2. 2.]
 [3. 1. 4.]]

Determinant:
-2.0

Rank:
3

Trace:
3

Eigenvalues and Eigenvectors:
(array([ 6.13131252, -0.28318599,  1.15187347]), array([[-0.57488477, -0.70804407,  0.07327836],
       [-0.44457759,  0.68866321, -0.82809722],
       [-0.68691941, -0.15625807,  0.55577449]]))

Inverse:
[[-3.   1.   2. ]
 [ 3.5 -0.5 -2.5]
 [-1.   0.   1. ]]


In [9]:
def read_complex():
    real = float(input("Enter real part: "))
    imag = float(input("Enter imaginary part: "))
    return complex(real, imag)


def conjugate_complex(z):
    return z.conjugate()

def complex_operations(z1, z2):
    addition = z1 + z2
    subtraction = z1 - z2
    multiplication = z1 * z2
    division = z1 / z2 if z2 != 0 else "Division by zero not allowed"
    return addition, subtraction, multiplication, division

def complex_as_vector(z):
    return (z.real, z.imag)


def magnitude_complex(z):
    return abs(z)



z1 = read_complex()
z2 = read_complex()

print("\nComplex number z1:", z1)
print("Complex number z2:", z2)

print("\nConjugate of z1:", conjugate_complex(z1))
print("Conjugate of z2:", conjugate_complex(z2))

add, sub, mul, div = complex_operations(z1, z2)

print("\nAddition:", add)
print("Subtraction:", sub)
print("Multiplication:", mul)
print("Division:", div)

print("\nComplex number as 2D vector:")
print("z1 →", complex_as_vector(z1))
print("z2 →", complex_as_vector(z2))

print("\nMagnitude of z1:", magnitude_complex(z1))
print("Magnitude of z2:", magnitude_complex(z2))





Enter real part: 3
Enter imaginary part: -2
Enter real part: 5
Enter imaginary part: 1

Complex number z1: (3-2j)
Complex number z2: (5+1j)

Conjugate of z1: (3+2j)
Conjugate of z2: (5-1j)

Addition: (8-1j)
Subtraction: (-2-3j)
Multiplication: (17-7j)
Division: (0.5-0.5j)

Complex number as 2D vector:
z1 → (3.0, -2.0)
z2 → (5.0, 1.0)

Magnitude of z1: 3.605551275463989
Magnitude of z2: 5.0990195135927845
